Traceback (most recent call last):
  File "/home/miuser/.local/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
[x,total_iter,t,x_plot] = primal_dual_method(fo, constraints_ineq,
                                             x_0, tol,
                                             tol_backtracking,
                                             t_B_0,
                                             x_ast=x_ast, 
                                             p_ast=p_ast, 
                                             max_inner_iter=max_inner_iter,
                                             mu=mu, 
                                             tol_outer_iter=tol_outer_iter,
                                             gf_B=gf_B,
                                             Hf_B=Hf_B,
                                             )
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mUnboundLocalError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-70-5dc11f05e34c>[0m in [0;36m<module>[0;34m[0m
[1;32m      9[0m                                              [0mtol_outer_iter[0m[0;34m=[0m[0mtol_outer_iter[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m                                              [0mgf_B[0m[0;34m=[0m[0mgf_B[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 11[0;31m                                              [0mHf_B[0m[0;34m=[0m[0mHf_B[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     12[0m                                              )

[0;32m~/.local/lib/python3.7/site-packages/opt/logarithmic_barrier/linear_program_inequalities.py[0m in [0;36mprimal_dual_method[0;34m(f, constraints_ineq, x_0, tol, tol_backtracking, t, plot, x_ast, p_ast, max_inner_iter, mu, gf_B, Hf_B, tol_outer_iter, max_total_iterations)[0m
[1;32m    149[0m                     [0mprint_iterations[0m[0;34m([0m[0mdata[0m[0;34m,[0m [0mcolumns[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    150[0m                     [0mprint[0m[0;34m([0m[0;34m"-"[0m[0;34m*[0m[0;36m65[0m [0;34m+[0m [0;34m"\n"[0m [0;34m+[0m [0;34m"-"[0m[0;34m*[0m[0;36m65[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 151[0;31m     [0;32mreturn[0m [0;34m[[0m[0mx[0m[0;34m,[0m[0mtotal_iter[0m[0;34m,[0m[0mt[0m[0;34m,[0m[0mx_plot_total_iter[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    152[0m [0;34m[0m[0m
[1;32m    153[0m def logarithmic_barrier_newton_method(f_B, constraints_ineq,

[0;31mUnboundLocalError[0m: local variable 'x_plot_total_iter' referenced before assignment
UnboundLocalError: local variable 'x_plot_total_iter' referenced before assignment

